- alias: "Ilmoitus kun sauna on lämmin"
  trigger:
    platform: numeric_state
    entity_id: sensor.sauna_temperature
    above: '60'
  action:
    - service: notify.ios
      data:
        message: "Saunan lämpötila on {{ states.sensor.sauna_temperature.state }} \xB0C"
        title: Sauna on lämmin
